name: epam-ci-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: build from script
      run: |
        ./scripts/build.sh
    
    - name: run test
      run: |
        ./scripts/test.sh
    
    - name: docker login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

    - name: build and push docker image
      run: |
        docker build -t ${{ secrets.DOCKER_LOGIN }}/epam-app:1.0 .
        docker push ${{ secrets.DOCKER_LOGIN }}/epam-app:1.0
